### ISSUE TITLE
sabers aren't correctly rotated & at wrists

### ISSUE THREAD

**Issue by 00scared** [im-henri/FingerSaber#12]
https://cdn.discordapp.com/attachments/441805394323439648/1276485421907443793/com.oculus.vrshell-20240823-131352.mp4?ex=66c9b330&is=66c861b0&hm=a7fdc664e3804140fff50680a05eba187cf93f1b798c40457063f4a0f8218726&

yeah

i'm on quest 2 1.37
90 hz

**Comment by im-henri** [comment]
I cannot see the video

**Comment by im-henri** [comment]
I assume this was fixed in discord help chat ?

**Comment by 00scared** [comment]
> I assume this was fixed in discord help chat ?

yes. i had to disable SmoothedController
