### ISSUE TITLE
HI me again!

### ISSUE THREAD

**Issue by TheKAPtain313** [im-henri/FingerSaber#13]
Um so it popped up with "continue with controllers" and i pressed continue even tho i did NOT have my controllers in my hand or turned on but it loaded any ways and i had no fingies :( plz fix or give me tutorial

**Comment by im-henri** [comment]
In the discord post there is "IMPORTANT" section which you probably did not check. "Will Not work without Hand-tracking permissions! Patch the game with hand-tracking permissions enabled. This can be done using MBF: tools tab -> change permissions -> "Hand tracking" -> repatch game". You can contact me directly from discord. I will close this issue as it is not really mod issue.

**Comment by TheKAPtain313** [comment]
can u give me an invite link?

**Comment by im-henri** [comment]
https://discord.gg/beatsabermods
