### ISSUE TITLE
A new cover.jpeg file (if you want it)

### ISSUE THREAD

**Issue by Austin-540** [im-henri/FingerSaber#3]
Hi, I noticed that the cover.jpeg file hasn't been changed since the initial commit, and I decided to try making one because I had nothing else to do today. 
Please let me know if you think there are any changes that could make it better, or if you aren't interested in updating the image.
Thanks

![finger-saber-icon](https://user-images.githubusercontent.com/105258719/202839484-ab38be0d-705f-4f94-9a47-5e7ad04c28f2.jpg)

**Comment by im-henri** [comment]
Hey, Thanks for the cover. I made the original one as a "joke" but never remembered to fix it. Ill will use your image if you wish. Otherwise it looks good, but maybe bigger font ?

**Comment by Austin-540** [comment]
I've come up with two versions with a bigger font

![fingersaber-biggerfont2](https://user-images.githubusercontent.com/105258719/202867147-347979ad-2bc3-4a1b-8f00-9521b739d304.jpg)

![fingersaber-biggerfont1](https://user-images.githubusercontent.com/105258719/202867156-daf01ef4-3c03-4bc0-8030-d3894cce47a2.jpg)

**Comment by im-henri** [comment]
I think original looks best as the the text is perfectly in the middle.

**Comment by Austin-540** [comment]
Ok, I went back to that one and made the text a bit bigger, and I made a new one where the text is centered between the edges of the hands

![newnewcover](https://user-images.githubusercontent.com/105258719/202867889-028f553f-bb43-4037-a916-98f54c2ef3c4.jpg)

![centredbetweenhands](https://user-images.githubusercontent.com/105258719/202867924-48c029b2-eab8-4980-8d7a-98966fddb242.jpg)

**Comment by im-henri** [comment]
Last one looks good, I'll change it to that.

**Comment by im-henri** [comment]
Added you to the credits of the Readme.
