### ISSUE TITLE
Toggle should be added for in-game hand smoothing + (BUG) hands offset to the right in newer release

### ISSUE THREAD

**Issue by Fazzoc** [im-henri/FingerSaber#6]
1st point (hand smoothing toggle)
Since the release of hand tracking 2.2, hand tracking response and latency has reduce significantly making it possible to play more fast paced tracks, but during gameplay, the in-game hand smoothing from the mod compromises the max speed that's capable with the latest update, not only that but since 2.1, meta added their own smoothing technique for hands which makes less sense to have it in game.
(except for q1 player and ui navigation, that why it should be a toggle)

https://github.com/im-henri/FingerSaber/assets/87571200/e250edbc-0973-4578-9c65-6153bb7bfce6 

Point 2: hand offset (0.1.5/latest bug)
i experienced an issue where in the latest update of the mod caused my hands to be offset to the right from where the hands actually are. not sure why it's happening but an older version (0.1.4) is not causing this.
![com beatgames beatsaber-20230801-135143](https://github.com/im-henri/FingerSaber/assets/87571200/8752b770-ae18-4f9d-b7a4-0ce74eaa106f)

**Comment by im-henri** [comment]
Thanks for detailed report.

For your first point (smoothed hands). The smoothed hand are only applied when you are in any of the menus. Inside of the game they are not enabled. So when you are in game, they are smoothed only when you are in the pause menu. 
For your note about hand tracking v2.2, I am fairly certain that it is not enabled by default. I currently do not have v56 quest firmware so I am unable to provide information on how to make it work with v2.2. I am eagerly waitin for my headset to get the update! But just like with v2.0, I am fairly sure it has to be patched manually. Once i get the update myself I will try to find a way to patch it and provide info in bsmg discord.
I can also add toggle for turning off the hand smoothing when in menus.

As for the second point, yes that is a bug. Good catch. I forgot to test "hands-only" mode.

I'll fix the bug and add toggle.

**Comment by Fazzoc** [comment]
Thanks for the reply! 
i didn't notice that it was a pause menu thing.
either way you're welcome! 😄

**Comment by im-henri** [comment]
Newer version is up in discord v0.1.6. Fixing the bug and adding toggle but also making performance better.
